POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IiIsImV4cCI6MTc0OTg0Mjc1OCwidXNlcklkIjoxfQ.9F3SRERs3rq1kSmXGagzu6JPKQL-ZErMm-GNCphI4Vk

{
  "name": "Event 1",
  "description": "This is the first event.",
  "location": "Buenos Aires",
  "dateTime": "2025-06-17T00:00:00Z"
}